### ISSUE TITLE
Error while downloading youtube videos .

### ISSUE THREAD

**Issue by ronin08** [vincreator/Eunha#11]
After migrating to ytdlp from ytdl , I am getting this error . I think the hack for changing extension is not working for ytdlp .

Here's the Error : 
[Errno 2] No such file or directory: '/usr/src/app/downloads/20269/Dhindora _ EP 04 - Saste Sherlock _ BB Ki Vines [Q9bsSQgBanc].webm'

Video link : https://youtu.be/Q9bsSQgBanc

**Comment by mbaktina** [comment]
![Screenshot_20211107-215906_Nekogram](https://user-images.githubusercontent.com/89569462/140650389-cdad67ba-1cd0-4074-bed1-84fe0fb8c19f.png)

![Screenshot_20211107-215954_Nekogram](https://user-images.githubusercontent.com/89569462/140650394-08adeb2a-e62b-43ae-8ef3-64140fabd4d1.png)

It's working on me 😗

**Comment by ronin08** [comment]
> ![Screenshot_20211107-215906_Nekogram](https://user-images.githubusercontent.com/89569462/140650389-cdad67ba-1cd0-4074-bed1-84fe0fb8c19f.png)
> 
> ![Screenshot_20211107-215954_Nekogram](https://user-images.githubusercontent.com/89569462/140650394-08adeb2a-e62b-43ae-8ef3-64140fabd4d1.png)
> 
> It's working on me 😗

It will download .. but before uploading the mentioned error will pop up !

**Comment by vincreator** [comment]
will check on log

**Comment by vincreator** [comment]
the leech it's working
but for gd it's not yet

**Comment by vincreator** [comment]
![Screenshot_20211107-221906_Nekogram](https://user-images.githubusercontent.com/54023694/140651043-a2539c47-53d0-4f1f-a4a7-47eb1d55789e.png)
it's not working on this link cus this 

Requested formats are incompatible for merge and will be merged into mkv

**Comment by xixugi** [comment]
okay will drop the hack think
cus ytdl is not fast we change to ytdlp

don't care about the auto format thing right? 😅

**Comment by ronin08** [comment]
> okay will drop the hack think cus ytdl is not fast we change to ytdlp
> 
> don't care about the auto format thing right? 😅

It's fixed now . Check the latest pull by that cool guy ! 
Merge it .
