### ISSUE TITLE
has been suspended 

### ISSUE THREAD

**Issue by ahmed98Osama** [vincreator/Eunha#14]
This is a notice to inform you that your Heroku app, mynewbot, has been suspended.

**Comment by xixugi** [comment]
read the readme

**Comment by ahmed98Osama** [comment]
"If got suspend apps after deploy just delete your apps and make it new with same name, then do `Container` again"
 
 i have done that for 3 or 4 times

**Comment by xixugi** [comment]
> "If got suspend apps after deploy just delete your apps and make it new with same name, then do `Container` again"
> 
> i have done that for 3 or 4 times

okay ... then do before get suspend
you make it apps again deploy... when workflows finish push image to heroku you must delete your apps quickly then make it new apps with same name and run the workflows again will not get suspend. it's work's.

remember.... don't wait until apps running and got suspend you must delete it before that
