### ISSUE TITLE
Featured Request 

### ISSUE THREAD

**Issue by RubanDurai** [vincreator/Eunha#18]
1. Add Force subscribe module
2. Status refresh button
3. Dump channel & pm support

**Comment by xixugi** [comment]
1. what Force subscribe module is?
2. status will auto refresh bro
3. what u mean for dump ch and pm support? (u can use the bot by pm btw)

**Comment by ghostmirrorlab** [comment]
> 1. what Force subscribe module is?
> 2. status will auto refresh bro
> 3. what u mean for dump ch and pm support? (u can use the bot by pm btw)

force sub repo
https://github.com/viperadnan-git/force-subscribe-telegram-bot

it basically mutes the memebers if the member have not joined the channel

and for the dump and pm support ig he ment

after mirror or leech, mirrored/leeched files will be sent to dump channel instted of sending it to the group
same for the pm support also ig
mirrored/leeched files will be directly sent to pm but for that bot should send "start me" msg if the user have not started the bot yet

**Comment by xixugi** [comment]
> > 1. what Force subscribe module is?
> > 2. status will auto refresh bro
> > 3. what u mean for dump ch and pm support? (u can use the bot by pm btw)
> 
> force sub repo https://github.com/viperadnan-git/force-subscribe-telegram-bot
> 
> it basically mutes the memebers if the member have not joined the channel
> 
> and for the dump and pm support ig he ment
> 
> after mirror or leech, mirrored/leeched files will be sent to dump channel instted of sending it to the group same for the pm support also ig mirrored/leeched files will be directly sent to pm but for that bot should send "start me" msg if the user have not started the bot yet

ok will soon
