### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by xon54** [vincreator/Eunha#20]
It's possible To use https://web3.storage as storage, i have no idea about but if you can it I'll be superb😀
Thanks

**Comment by xixugi** [comment]
> It's possible To use https://web3.storage as storage, i have no idea about but if you can it I'll be superb😀 Thanks

the web3.storage use js
I don't know about it implemented in python

**Comment by xixugi** [comment]
> It's possible To use https://web3.storage as storage, i have no idea about but if you can it I'll be superb😀 Thanks

the best possibility is use shell to run it cus the shell can acces https right? i don't know man hehe
use curl think
