### ISSUE TITLE
Error "run_async"

### ISSUE THREAD

**Issue by ZxcGitt** [vincreator/Eunha#26]
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    **mod_name, mod_spec, code = _get_module_details(mod_name, _Error)**
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    **return _get_module_details(pkg_main_name, error)**
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/src/app/bot/__init__.py", line 447, in <module>
    tgDefaults = Defaults(parse_mode='HTML', disable_web_page_preview=True, allow_sending_without_reply=True, run_async=True)
**TypeError: __init__() got an unexpected keyword argument 'run_async'**

please fix it

**Comment by xixugi** [comment]
use python-telegram-bot==13.15 on requirements.txt then redeploy.
sorry for that but i still type a code for next update and test it

**Comment by xixugi** [comment]
> Traceback (most recent call last): File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main **mod_name, mod_spec, code = _get_module_details(mod_name, _Error)** File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details **return _get_module_details(pkg_main_name, error)** File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details **import**(pkg_name) File "/usr/src/app/bot/**init**.py", line 447, in tgDefaults = Defaults(parse_mode='HTML', disable_web_page_preview=True, allow_sending_without_reply=True, run_async=True) **TypeError: **init**() got an unexpected keyword argument 'run_async'**
> 
> please fix it

all fixed
