### ISSUE TITLE
/qb s doesn't work? #Question

### ISSUE THREAD

**Issue by Topkek6969** [vincreator/eunha#7]
Using /qb s takes me to my app heroku page but it gives error, so is qb select support not there?

**Comment by vincreator** [comment]
it's working fine to me

**Comment by xixugi** [comment]
> 
> 
> Using /qb s takes me to my app heroku page but it gives error, so is qb select support not there?

it's working fine to me i select and press "kirim" then press done selecting on telegram

**Comment by Topkek6969** [comment]
> > Using /qb s takes me to my app heroku page but it gives error, so is qb select support not there?
> 
> it's working fine to me i select and press "kirim" then press done selecting on telegram

Oh, alright maybe I messed with the code a bit too much, sorry for disturbing.
