### ISSUE TITLE
getting error while deploying

### ISSUE THREAD

**Issue by askfriends** [vincreator/Eunha#9]
im getting this error in github workflows while deploying

`Run heroku container:push "${IMAGE_NAME}" -a "${HEROKU_APP_NAME}"
 ›   Warning: heroku update available from 7.59.0 to 7.59.1.
 ▸    Couldn't find that app.
Error: Process completed with exit code 1.`

i have changed app name and tried few unique names but still same error

**Comment by gudmeong** [comment]
> im getting this error in github workflows while deploying
> 
> `Run heroku container:push "${IMAGE_NAME}" -a "${HEROKU_APP_NAME}" › Warning: heroku update available from 7.59.0 to 7.59.1. ▸ Couldn't find that app. Error: Process completed with exit code 1.`
> 
> i have changed app name and tried few unique names but still same error

Are you sure?, mine fine

**Comment by askfriends** [comment]
> > im getting this error in github workflows while deploying
> > `Run heroku container:push "${IMAGE_NAME}" -a "${HEROKU_APP_NAME}" › Warning: heroku update available from 7.59.0 to 7.59.1. ▸ Couldn't find that app. Error: Process completed with exit code 1.`
> > i have changed app name and tried few unique names but still same error
> 
> Are you sure?, mine fine

yeah, i tried several times and got same error

**Comment by gudmeong** [comment]
> > > im getting this error in github workflows while deploying
> > > `Run heroku container:push "${IMAGE_NAME}" -a "${HEROKU_APP_NAME}" › Warning: heroku update available from 7.59.0 to 7.59.1. ▸ Couldn't find that app. Error: Process completed with exit code 1.`
> > > i have changed app name and tried few unique names but still same error
> > 
> > 
> > Are you sure?, mine fine
> 
> yeah, i tried several times and got same error

Ok, lemme test now

**Comment by gudmeong** [comment]
> > > im getting this error in github workflows while deploying
> > > `Run heroku container:push "${IMAGE_NAME}" -a "${HEROKU_APP_NAME}" › Warning: heroku update available from 7.59.0 to 7.59.1. ▸ Couldn't find that app. Error: Process completed with exit code 1.`
> > > i have changed app name and tried few unique names but still same error
> > 
> > 
> > Are you sure?, mine fine
> 
> yeah, i tried several times and got same error

Bro, first create your app in heroku, after that fill a name to secrets. this is missing in guide workflow methode, thanks for reporting

**Comment by askfriends** [comment]
> > > > im getting this error in github workflows while deploying
> > > > `Run heroku container:push "${IMAGE_NAME}" -a "${HEROKU_APP_NAME}" › Warning: heroku update available from 7.59.0 to 7.59.1. ▸ Couldn't find that app. Error: Process completed with exit code 1.`
> > > > i have changed app name and tried few unique names but still same error
> > > 
> > > 
> > > Are you sure?, mine fine
> > 
> > 
> > yeah, i tried several times and got same error
> 
> Bro, first create your app in heroku, after that fill a name to secrets. this is missing in guide workflow methode, thanks for reporting

oh i see. will do that.
IT would be nice if u mention that in guide or readme.

**Comment by gudmeong** [comment]
> > > > > im getting this error in github workflows while deploying
> > > > > `Run heroku container:push "${IMAGE_NAME}" -a "${HEROKU_APP_NAME}" › Warning: heroku update available from 7.59.0 to 7.59.1. ▸ Couldn't find that app. Error: Process completed with exit code 1.`
> > > > > i have changed app name and tried few unique names but still same error
> > > > 
> > > > 
> > > > Are you sure?, mine fine
> > > 
> > > 
> > > yeah, i tried several times and got same error
> > 
> > 
> > Bro, first create your app in heroku, after that fill a name to secrets. this is missing in guide workflow methode, thanks for reporting
> 
> oh i see. will do that. IT would be nice if u mention that in guide or readme.

Yeah, missing something text on readme😂 thanks for your attention, now you can close this issue😁
